### ISSUE TITLE
new Forge release checklist

### ISSUE THREAD

**Issue by jhoblitt** [voxpupuli/puppet-jenkins#855]
- [ ] revert new CLI interface #854 
- [ ] remove big scary warning about native types from readme #856 
- [ ] Rubocop + modulesync + whatever from the voxpupuli switch - @alexjfisher 
- [ ] make release

**Comment by PierreR** [comment]
The puppet forge release dated from Aug 17, 2016. Just hope the new release will happen soon than later ;-)

**Comment by ljohnston** [comment]
Please? I thought the move to voxpupuli was going to address the stale releases issue.

**Comment by rtyler** [comment]
@ljohnston puppet-jenkins is an open source project and is worked on by volunteers who have their own jobs and responsibilities. If a new forge release is important to you, I recommend finding ways to help make it happen (see related issues).

**Comment by bastelfreak** [comment]
A new release depends on https://github.com/voxpupuli/puppet-jenkins/pull/879. The tests currently don't work on modern ruby or puppet 5. Patches for that are highly appreciated. Feel free to join our IRC channel #voxpupuli on freenode or our slack channel at https://puppetcommunity.slack.com if you want to participate!

**Comment by ekohl** [comment]
There are separate issues now linked to the 2.0.0 milestone. Closing this now.
